### ISSUE TITLE
SPP-R310 support

### ISSUE THREAD

**Issue by pietervw** [alfonsovinti/cordova-plugin-bixolon-print#11]
Hi, the SPP-R300 has been replaced with the SPP-R310, however the plugin doesn't seem to work for that model. 

I have added an entry for MAX_COL:
        `put("SPP-R310", 48);`

I get error "Cannot connect" when trying to connect via Bluetooth. In never changes state to "STATE_CONNECTED"

Any idea how I can address this problem?

Thank you

**Comment by alfonsovinti** [comment]
Hi,

Yes to fix this error you need to upgrade the SDK.

I hope to push an update in the next few days.

Regards

**Comment by pietervw** [comment]
Thank you @alfonsovinti.

I have tried replacing the BixolonPrinter.jar file with bixolon_printer_v1211.jar which I found from the Android SDK [http://www.bixolon.com/html/en/download/download_product.xhtml?prod_id=111](here). I have also renamed the new file to BixolonPrinter.jar for the plugin.

Unfortunately I get build errors and I am not at all proficient in Java. If you can assist I'll greatly appreciate it.

**Comment by alfonsovinti** [comment]
This is the SDK for Android [http://www.bixolon.com/upload/download/software_all_bixolon_printer_sdk_for_android_v2.3.0.zip](http://www.bixolon.com/upload/download/software_all_bixolon_printer_sdk_for_android_v2.3.0.zip)

and this for iOS [http://www.bixolon.com/upload/download/bixolon%20ios%20sdk%20v3.1.14_20160428.zip](http://www.bixolon.com/upload/download/bixolon%20ios%20sdk%20v3.1.14_20160428.zip)

**Comment by pietervw** [comment]
@alfonsovinti you're a lifesaver! That worked a charm. Thank you very much! I was using the wrong SDK all along. 

Thanks again

**Comment by alfonsovinti** [comment]
Happy to know the problem is solved.

You are welcome.
