### ISSUE TITLE
Font size text cordova.plugins.bixolonPrint.printText

### ISSUE THREAD

**Issue by lucav90** [alfonsovinti/cordova-plugin-bixolon-print#15]
Hi,

how can i change the font size of text printing with cordova.plugins.bixolonPrint.printText?

regards,

**Comment by alfonsovinti** [comment]
Hi,
you need to use textWidth and textHeight properties.

```
cordova.plugins.bixolonPrint.addLine({
    text: "hello cordova!",
    textWidth  : cordova.plugins.bixolonPrint.TextDimension.TD_2,
    textHeight : cordova.plugins.bixolonPrint.TextDimension.TD_2
});
```
Value range is from TextDimension.TD_0 to TextDimension.TD_7

Regards
