### ISSUE TITLE
Bixolon Printer

### ISSUE THREAD

**Issue by subahanma** [alfonsovinti/cordova-plugin-bixolon-print#2]
Hi alfonsovinti,

Thanks for your plugin. It works great.

Actually not reporting any issues instead requesting for enhancements. I need your help to extend this to include the below features.
1. Line spacing between each line. 
2. Print Image

Hope you would be able to spare sometime to fix these.

Regards
Abdul

**Comment by juancamilovaes** [comment]
Hi Abdul.

I am working with phonegap in an app for android with javascript. I have a Bixolon SPP-R200II and i don't know how to use correctly this plugin. I just need to print a couple lines as a ticket.

Can you help me with a more structured example of plugin's use? I'll really aprecciate it. Thanks a lot.

**Comment by subahanma** [comment]
Hi,
I did this.
1. Added the cordova-plugin-bixolon-print plugin.2. In my app, I have two buttons.    a. connect button. Its click event has get status of printer as below.           try {
              cordova.plugins.bixolonPrint.getStatus(                 function() {
 connected = true; //my own local variable
                 }, 
                 function() {
                    connected = false; //my own local variable
                 },                 false             );            }            catch (err) {   connected = false;  //my own local variable                       }
Note : I need to click this 4 times. 1st time it challenges for the bluetooth pairing code. 2 & 3 times, it seems handshaking and 4th time only it returns connected status as true.
    b. print button. Its click event has below code.
    var lineObj = {         text       : "              Test Printing                 "+ "\n",         textAlign  : 'left',  // or 'left' 'right'  'center'         textWidth  : 0,  // 0-7         textHeight : 0,  // 0-7         fontType   : 'A',  // 'A' 'B'         fontStyle  : 'default'  // or 'default' 'bold' 'underlined'  'reversed'     };     cordova.plugins.bixolonPrint.addLine(lineObj);
     cordova.plugins.bixolonPrint.printText(null, null);
It prints fine. 
Note : My printer is SPP-R300
Hope this helps you.
Abdul 

```
 On Wednesday, July 1, 2015 6:27 AM, juan camilo valencia <notifications@github.com> wrote:
```

 Hi Abdul.I am working with phonegap in an app for android with javascript. I have a Bixolon SPP-R200II and i don't know how to use correctly this plugin. I just need to print a couple lines as a ticket.Can you help me with a more structured example of plugin's use? I'll really aprecciate it. Thanks a lot.—

**Comment by juancamilovaes** [comment]
Hi Abdul, it doesn't work for me, i don't know what i'm doing wrong. I just put the "gap" on my config.xml and I tried to use it. I also tried getting the bixolon.js into my project's js folder and call it from my index scripts, and nothing worked. Can you help me, how I have to use it, I've tried everything and nothing works. This is my code:

<script type="text/javascript" src="js/bixolonprint.js"></script>

```
    <script>
        function Print()
        {
             var lineObj = {
                text: "Test Printing",
                textAlign  : 'left',
                textWidth  : 0,
                textHeight : 0,
                fontType   : 'A',
                fontStyle  : 'default'};

            console.log('printing');

            cordova.plugins.BixolonPrint.addLine(lineObj);
            cordova.plugins.BixolonPrint.printText(null, null);
            console.log('printed');
        }

        function attemptPrintConnection()
        {
            try 
            {
                cordova.plugins.BixolonPrint.getStatus(function() 
                    {
                        var connected = true; //my own local variable
                        console.log('Conectada');
                        console.log(connected);
                    },function() 
                    {
                        var connected = false; //my own local variable
                        console.log('intentando conectar');
                        console.log(connected);
                    },false);
            }

            catch (err) 
            {   
                var connected = false;  //my own local variable
                console.log('intentando conectar');
                console.log(connected);
            }
        }

    </script>
```

**Comment by subahanma** [comment]
Actually you don't need to include the bixolonprint.js at index.html. The plugins will be included when it is built.
Make sure you call the connect printer before printing. If so, does it prompt to pair? Also noticed the plugin is referred as cordova.plugins.BixolonPrint instead of cordova.plugins.bixolonPrint 
Pls change spelling and try.

```
 On Monday, July 6, 2015 6:59 AM, juan camilo valencia <notifications@github.com> wrote:
```

 Hi Abdul, it doesn't work for me, i don't know what i'm doing wrong. I just put the "gap" on my config.xml and I tried to use it. I also tried getting the bixolon.js into my project's js folder and call it from my index scripts, and nothing worked. Can you help me, how I have to use it, I've tried everything and nothing works. This is my try code:    <script>
        function Print()
        {
             var lineObj = {
                text: "Test Printing",
                textAlign  : 'left',
                textWidth  : 0,
                textHeight : 0,
                fontType   : 'A',
                fontStyle  : 'default'};

```
        console.log('imprimiendo');

        cordova.plugins.BixolonPrint.addLine(lineObj);
        cordova.plugins.BixolonPrint.printText(null, null);
        /*var siImprimio = "si";

        dbShell.transaction(function(tx) 
        {  
            tx.executeSql("Update UsuariosServicios set impreso=? where Numero=?",[siImprimio,numero], 
            function(tx, result)
            {
                document.getElementById("txtImpreso").value = siImprimio;
                permitirEditar();
            });
        });*/

        console.log('impreso');
    }

    function attemptPrintConnection()
    {
        try 
        {
            cordova.plugins.BixolonPrint.getStatus(function() 
                {
                    var connected = true; //my own local variable
                    console.log('Conectada');
                    console.log(connected);
                },function() 
                {
                    var connected = false; //my own local variable
                    console.log('intentando conectar');
                    console.log(connected);
                },false);
        }

        catch (err) 
        {   
            var connected = false;  //my own local variable
            console.log('intentando conectar');
            console.log(connected);
        }
    }

</script>
```

**Comment by alfonsovinti** [comment]
Hello, sorry for my late response, I have some news for you. In a few days I will update the plugin adding these features:
New Android api, black marker and lable mode, charset and some change on javascript api.

Please wait a few days for the update.

**Comment by subahanma** [comment]
Hi, Any update on the new version. 
Thanks 
Abdul 

```
 On Friday, July 10, 2015 9:08 PM, Alfonso Vinti <notifications@github.com> wrote:
```

 Hello, sorry for my late response, I have some news for you. In a few days I will update the plugin adding these features:
New Android api, black marker and lable mode, charset and some change on javascript api.Please wait a few days for the update.—

**Comment by Aeon1** [comment]
Thanks alfonsovinti you save my life with your plugin.
I want to know if you have thinking add to print images with the plugin?

**Comment by vinfo** [comment]
Hello everyone, In this moment I need to print in Bixolon SPP-R200II.
I tried this plugin in phone app; but always I received this messages:

“TypeError: Cannot read property ‘bixolonPrint’ of undefined”.

I used build phonegap sintax.

The code sentences are:

cordova.plugins.bixolonPrint.getStatus(function()
{
var connected = true; //my own local variable
alert(‘Conectada’);
},function()
{
var connected = false; //my own local variable
alert(‘Fallo al conectar’);
},false);

What is the problem??

**Comment by Aeon1** [comment]
the function it's ok maybe your problem is in the integration of the plugins or cordova

**Comment by vinfo** [comment]
Simple, I add this line at my config.xml and build on phonegag web:
<gap:plugin name="it.alfonsovinti.cordova.plugins.bixolonprint" version="1.3.0" />

Exists other step to implement?? I follow the simple instructions on the phonegap plug in implement. 
Tk, for any help

**Comment by vinfo** [comment]
<gap:plugin name="it.alfonsovinti.cordova.plugins.bixolonprint" version="1.3.0" />

**Comment by alfonsovinti** [comment]
Hi, did you follow plugin guide and installed it with CLI?

**Comment by vinfo** [comment]
Hello, I tried only used the compilation in Phonegap build with add the
line plugin in the config.xml:

<gap:plugin name="it.alfonsovinti.cordova.plugins.bixolonprint"
version="1.3.0" />

Is better by CLI method??

2015-08-31 14:42 GMT-05:00 Alfonso Vinti notifications@github.com:

**Comment by alfonsovinti** [comment]
Plugin can be installed only through Cordova/PoneGap CLI or plugman, follow the Readme to install it. Furthermore it is good practice using CLI for your app management. Let me know ;)

**Comment by vinfo** [comment]
I installled via CLI by phonegap with this sentence:

_$ phonegap local plugin add
https://github.com/alfonsovinti/cordova-plugin-bixolon-print.git
https://github.com/alfonsovinti/cordova-plugin-bixolon-print.git_

And the test connection show me this message:

*"TypeError: Cannot read property 'bixolonPrint' *

_of undefined"_

The code for this test:

_"    try     {      cordova.plugins.bixolonPrint.getStatus(function()
      {                        var connected = true; //my own local
variable                        alert('Conectada');
  },function()                       {                        var
connected = false; //my own local variable
alert('Fallo al conectar');                      },false);    }
catch (err)     {         alert("Error "+err);    }"_

2015-08-31 15:26 GMT-05:00 Alfonso Vinti notifications@github.com:

**Comment by juancamilovaes** [comment]
Hi,

I would like to know if this plugin has some method for to print images and how I can use it. someone knows if it is possible?

Thank you and regards,
Juan Camilo

**Comment by pietervw** [comment]
Hi @juancamilovaes  and @alfonsovinti .

Is there a way to print images with this plugin?

**Comment by pietervw** [comment]
@subahanma I've made a fork that can print images. 

Check it out [here](https://github.com/pietervw/cordova-plugin-bixolon-print)

**Comment by Armis-Code** [comment]
Buenos días tengo una duda referente a la impresión estoy utilizando una impresora BIXALON Modelo SRP-350/352plus III y implemente el código  @alfonsovinti pero al realizar la conexion manda el error this device cannot be claimed for exclusive access  alguien me puede ayudar
