### ISSUE TITLE
Help with Bixolon plugin

### ISSUE THREAD

**Issue by juancamilovaes** [alfonsovinti/cordova-plugin-bixolon-print#3]
Hi!.

I am working with phonegap in an app for android with javascript. I have a Bixolon SPP-R200II and i don't know how to use correctly this plugin. I just need to print a couple lines as a ticket.

Can you help me with a more structured example of plugin's use? I'll really aprecciate it. Thanks a lot.

**Comment by pietervw** [comment]
@juancamilovaes I've made a fork that can print images. 

Check it out [here](https://github.com/pietervw/cordova-plugin-bixolon-print)
