### ISSUE TITLE
How to work with the plugin?

### ISSUE THREAD

**Issue by safanmomin** [alfonsovinti/cordova-plugin-bixolon-print#8]
Hello, I am using this plugin and I don't know how to implement it. I am working with phonegap and I have a Bixolon SRP-350II (It's a usb printer). Can you help me with a example of how to use this plugin? It can really kickstart my stuff here. Thanks alot!

**Comment by alfonsovinti** [comment]
Hello, sorry for the late reply. The plugin works only with bluetooth connections so you need to find out if your printer may be connected via bluetooth. 
If you have other questions please feel free to contact me again.
Best regards
